name: Uptime Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

env:
  BACKEND_URL: https://voice-cloning-backend-prod.azurewebsites.net/health
  FUNCTIONS_URL: https://voice-cloning-functions-prod.azurewebsites.net/api/health
  FRONTEND_URL: https://voice-cloning-frontend-prod.azurewebsites.net/

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check backend health
        run: |
          curl -fsS $BACKEND_URL
      - name: Check functions health
        run: |
          curl -fsS $FUNCTIONS_URL
      - name: Check frontend
        run: |
          curl -fsS $FRONTEND_URL

